# Web scraping Transfermarkt
# ENGLISH PREMIER LEAGUE Market Value
## The 100 most valuable players

In [ ]:
# Import libraries
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin


links = []
data_market = []
page_total = 5

for page in range(1, page_total):
    new_url = f"https://www.transfermarkt.com/premier-league/marktwerte/wettbewerb/GB1/ajax/yw1/pos//detailpos/0/altersklasse/alle/plus/1/page/{page}"
    links.append(new_url)


for link in links:
    headers = ({'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36', 'Accept-Language': 'en-US, en;q=0.5'})
    #url_1 = f"https://www.transfermarkt.com/premier-league/marktwerte/wettbewerb/GB1/ajax/yw1/pos//detailpos/0/altersklasse/alle/plus/1/page/{page_actual}"
    url_actual = link
    print(url_actual)
    #url_actual = f"https://www.transfermarkt.com/premier-league/marktwerte/wettbewerb/GB1/ajax/yw1/pos//detailpos/0/altersklasse/alle/plus/1/page/{page_actual}"
    page = requests.get(url_actual, headers=headers)
    soup = BeautifulSoup(page.text, "html.parser")
    table = soup.find(id='yw1')

    
        
# Scrape info
    
    # PLAYER NAME
    players_name = table.find_all('td', {'class':"hauptlink"})
    all_players = [player.text.strip() for player in players_name][::2]
    
    # MARKET VALUE
    market_val = table.find_all('td', {'class':"rechts hauptlink"})
    market_value = [value.text.strip() for value in market_val]
    
    # COUNTRY
    country_players = [] # List that will receive all the names of the countries of the players’s previous leagues.
    tags_league = table.find_all("td",{"class": 'zentriert'})
    
    # Now we will receive all the cells in the table that have no class atribute set
    for tag_league in tags_league:
        # The find() function will find the first image whose class is "flaggenrahmen" and has a title
        img_country = tag_league.find("img", {"class": "flaggenrahmen"}, {"title":True})
        # The country_image variable will be a structure with all the image information,
        # one of them is the title that contains the name of the country of the flag image
        if(img_country != None): # We will test if we have found any matches than add them
            country_players.append(img_country['title'])
    
    # TEAMS
    team_players = [] # List that will receive all the names of the countries of the players’s previous leagues.
    teams = table.find_all("td",{"class": 'zentriert'})
    for team in teams:
        # The find() function will find the first image whose class is "flaggenrahmen" and has a title
        img_team = team.find("a", {"class": None}, {"title":True})
        # The country_image variable will be a structure with all the image information,
        # one of them is the title that contains the name of the country of the flag image
        if(img_team != None): # We will test if we have found any matches than add them
            team_players.append(img_team['title'])
    

    market = pd.DataFrame({
        
        'Player Name': all_players, 
        'Market Value': market_value, 
        'Country': country_players,
        'Team': team_players
    })
    data_market.append(market)
    
data_market = pd.concat(data_market)


# Export to Excel
data_market.to_excel("EPL 100 Most Valuable Players (June 2023).xlsx")

In [211]:
data_market.head(100)

        Player Name Market Value   Country              Team
0    Erling Haaland     €180.00m    Norway   Manchester City
1       Bukayo Saka     €120.00m   England        Arsenal FC
2        Phil Foden     €110.00m   England   Manchester City
3   Martin Ødegaard      €90.00m    Norway        Arsenal FC
4       Declan Rice      €90.00m   England   West Ham United
..              ...          ...       ...               ...
20       Marc Guéhi      €35.00m   England    Crystal Palace
21   Miguel Almirón      €32.00m  Paraguay  Newcastle United
22  Conor Gallagher      €32.00m   England        Chelsea FC
23      Roméo Lavia      €32.00m   Belgium    Southampton FC
24  Kalvin Phillips      €32.00m   England   Manchester City

[100 rows x 4 columns]

In [212]:
data = data_market
data

        Player Name Market Value   Country              Team
0    Erling Haaland     €180.00m    Norway   Manchester City
1       Bukayo Saka     €120.00m   England        Arsenal FC
2        Phil Foden     €110.00m   England   Manchester City
3   Martin Ødegaard      €90.00m    Norway        Arsenal FC
4       Declan Rice      €90.00m   England   West Ham United
..              ...          ...       ...               ...
20       Marc Guéhi      €35.00m   England    Crystal Palace
21   Miguel Almirón      €32.00m  Paraguay  Newcastle United
22  Conor Gallagher      €32.00m   England        Chelsea FC
23      Roméo Lavia      €32.00m   Belgium    Southampton FC
24  Kalvin Phillips      €32.00m   England   Manchester City

[100 rows x 4 columns]

In [298]:

new_url = f"https://www.transfermarkt.com/premier-league/marktwerte/wettbewerb/GB1/ajax/yw1/pos//detailpos/0/altersklasse/alle/plus/1/page/1"
links.append(new_url)



headers = ({'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36', 'Accept-Language': 'en-US, en;q=0.5'})
#url_1 = f"https://www.transfermarkt.com/premier-league/marktwerte/wettbewerb/GB1/ajax/yw1/pos//detailpos/0/altersklasse/alle/plus/1/page/{page_actual}"
url_actual = new_url
print(url_actual)
#url_actual = f"https://www.transfermarkt.com/premier-league/marktwerte/wettbewerb/GB1/ajax/yw1/pos//detailpos/0/altersklasse/alle/plus/1/page/{page_actual}"
page = requests.get(url_actual, headers=headers)
soup = BeautifulSoup(page.text, "html.parser")
table = soup.find(id='yw1')

    
        
# Obtenemos la info
# PLAYER NAME

positions = table.find_all('table', {'class':"hauptlink"})
positions
    
#all_pos = [position.text.strip() for position in positions][::2]

https://www.transfermarkt.com/premier-league/marktwerte/wettbewerb/GB1/ajax/yw1/pos//detailpos/0/altersklasse/alle/plus/1/page/1

[]

In [286]:
all_pos

['Erling Haaland \n\n\nCentre-Forward',
 'Phil Foden \n\n\nLeft Winger',
 'Declan Rice \n\n\nDefensive Midfield',
 'Harry Kane \n\n\nCentre-Forward',
 'Bernardo Silva \n\n\nAttacking Midfield',
 'Marcus Rashford \n\n\nLeft Winger',
 'Luis Díaz \n\n\nLeft Winger',
 'Moisés Caicedo \n\n\nDefensive Midfield',
 'Jack Grealish \n\n\nLeft Winger',
 'Kevin De Bruyne \n\n\nAttacking Midfield',
 'Alexis Mac Allister \n\n\nAttacking Midfield',
 'Trent Alexander-Arnold \n\n\nRight-Back',
 'Reece James \n\n\nRight-Back']